/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gmasoftware.sellersystem.sales;

import com.gmasoftware.sellersystem.database.DB;
import com.gmasoftware.sellersystem.user.User;
import java.awt.event.ActionEvent;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.BoxLayout;
import javax.swing.JButton;

/**
 *
 * @author GMA Software
 */
public class RegisterSaleForm extends javax.swing.JFrame{
    private final User user;
    private ProductBlock[] productBlocksClass;

    /**
     * Creates new form RegisterNewSale
     */
    public RegisterSaleForm() {
        user = User.getInstance();
        
        initComponents();
        this.setLocationRelativeTo(null);
        
        productListContainerFactory();
        addAProductBlock();
        
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        productListContainer = new javax.swing.JScrollPane();
        productBlocksContainer = new javax.swing.JPanel();

        jLabel3.setText("jLabel3");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel6.setText("jLabel6");

        jLabel1.setText("Register new sale");

        submitButton.setText("Accept");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Total");

        productBlocksContainer.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout productBlocksContainerLayout = new javax.swing.GroupLayout(productBlocksContainer);
        productBlocksContainer.setLayout(productBlocksContainerLayout);
        productBlocksContainerLayout.setHorizontalGroup(
            productBlocksContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
        );
        productBlocksContainerLayout.setVerticalGroup(
            productBlocksContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
        );

        productListContainer.setViewportView(productBlocksContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(productListContainer))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jLabel5)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productListContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 245, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(19, 19, 19)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Here will be the product blocks with their name, price, units and subtotal.
     */
    private void productListContainerFactory(){
        productBlocksContainer.setBackground(new java.awt.Color(205, 205, 205));
        productBlocksContainer.setLocation(0,0);
        var productBlocksContainerLayout = new BoxLayout(productBlocksContainer, BoxLayout.Y_AXIS);
        productBlocksContainer.setLayout(productBlocksContainerLayout);
        
        JButton addProductButton = new JButton();
        addProductButton.setText("Añadir producto");
        addProductButton.addActionListener((ActionEvent arg0) -> {            
            addAProductBlock();
        });
        productBlocksContainer.add(addProductButton);
        
        productListContainer.setLocation(0,0);
        productListContainer.setSize(611, 350);
        productListContainer.setViewportView(productBlocksContainer);
    }

    /**
     * Place a new product block on the form. 
     * For each different product there will be one of these blocks with the name 
     * of the product, its price, units and subtotal.
     */
    private void addAProductBlock(){
        var productBlock = new ProductBlock();
        productBlocksContainer.add(productBlock);
//        products = {
//        };
    }
    
    /***
     * Register a new sale.
     * @param evt Event object
     */
    private void submitButtonHandler(java.awt.event.ActionEvent evt0){
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        var now = dtf.format(LocalDateTime.now());
        
        var db = new DB();
        db.connect();
        
        String[] keys = {"totalAmount","totalProductCount","date","productList","productUnits","user"};
        String[] valuesToInsert = {
            "3500",
            "4",
            String.valueOf(now),
            "4,5",
            "3,1",
            String.valueOf(user.getUsername())
        };
        db.insert("sales", keys, valuesToInsert);
    }
    
    
    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
      submitButtonHandler(evt);
    }//GEN-LAST:event_submitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterSaleForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel productBlocksContainer;
    private javax.swing.JScrollPane productListContainer;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
