/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gmasoftware.sellersystem.sales;

import com.gmasoftware.sellersystem.database.DB;
import com.gmasoftware.sellersystem.user.User;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.BoxLayout;
import javax.swing.JButton;

/**
 *
 * @author GMA Software
 */
public class RegisterSaleForm extends javax.swing.JFrame{
    private final User user;
    private ProductBlock[] productBlocks = {};

    /**
     * Creates new form RegisterNewSale
     */
    public RegisterSaleForm() {
        user = User.getInstance();
        
        initComponents();
        this.setLocationRelativeTo(null);
        
        productListContainerFactory();
        addAProductBlock();
        
        JButton addProductButton = new JButton();
        addProductButton.setText("Añadir producto");
        addProductButton.addActionListener((ActionEvent arg0) -> {            
            addAProductBlock();
        });
        actionBar.add(addProductButton);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        totalTitle = new javax.swing.JLabel();
        productListContainer = new javax.swing.JScrollPane();
        productBlocksContainer = new javax.swing.JPanel();
        total = new javax.swing.JLabel();
        actionBar = new javax.swing.JPanel();

        jLabel3.setText("jLabel3");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel6.setText("jLabel6");

        jLabel1.setText("Register new sale");

        submitButton.setText("Accept");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        totalTitle.setText("Total");

        productBlocksContainer.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout productBlocksContainerLayout = new javax.swing.GroupLayout(productBlocksContainer);
        productBlocksContainer.setLayout(productBlocksContainerLayout);
        productBlocksContainerLayout.setHorizontalGroup(
            productBlocksContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
        );
        productBlocksContainerLayout.setVerticalGroup(
            productBlocksContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
        );

        productListContainer.setViewportView(productBlocksContainer);

        total.setText("0");

        actionBar.setPreferredSize(new java.awt.Dimension(0, 45));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(301, 301, 301)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(totalTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                    .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productListContainer, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(actionBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productListContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actionBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(totalTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(total)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Here will be the product blocks with their name, price, units and subtotal.
     */
    private void productListContainerFactory(){
        productBlocksContainer.setBackground(new java.awt.Color(205, 205, 205));
        productBlocksContainer.setLocation(0,0);
        var productBlocksContainerLayout = new BoxLayout(productBlocksContainer, BoxLayout.Y_AXIS);
        productBlocksContainer.setLayout(productBlocksContainerLayout);
        
        productListContainer.setLocation(0,0);
        productListContainer.setSize(611, 350);
        productListContainer.setViewportView(productBlocksContainer);
    }

    /**
     * Place a new product block on the form. 
     * For each different product there will be one of these blocks with the name 
     * of the product, its price, units and subtotal.
     */
    private void addAProductBlock(){
        var productBlock = new ProductBlock(this);
        
        // Events for Enter and Ctrl + Enter.
        productBlock.getProductUnits().addKeyListener(new KeyListener(){
            @Override
            public void keyTyped(KeyEvent e){}
            @Override
            public void keyPressed(KeyEvent e){
                // Enter
                if(e.getKeyCode() == KeyEvent.VK_ENTER){
                    productBlock.calculateSubtotal();
                    System.out.println("Indice: "+ productBlock.getIndexInContainer());
                }
                // Ctrl + Enter
                if(e.isControlDown() && e.getKeyCode() == KeyEvent.VK_ENTER){
                    addAProductBlock();
                }
            }
            @Override
            public void keyReleased(KeyEvent e){}
        });
        
        productBlocksContainer.add(productBlock);//add the productBlock to the container
        
        var productBlocksLength = productBlocks.length;
        //It's the product blocks array with a new place for the new product block.
        ProductBlock[] newArray = new ProductBlock[productBlocksLength +1];
        
        //Copy all the elements from the old array to the new array.
        System.arraycopy(productBlocks, 0, newArray, 0, productBlocksLength);
        
        //Add the new element (the new product block)
        productBlock.setIndexInContainer(productBlocksLength);
        newArray[productBlocksLength] = productBlock;
        
        productBlocks = newArray;
        
        //Event to remove the product block.
        productBlock.getRemoveButton().addActionListener((ActionEvent ActionListener) -> {
            var oldProductBlocksLength = productBlocks.length;
            
            //It's the new array of product blocks with one less place.
            var newArraySize = (oldProductBlocksLength -1) > 0 ? (oldProductBlocksLength -1) : 0;
            
            ProductBlock[] newArray1 = new ProductBlock[newArraySize];
            int indexCounter = 0;
            
            for (int i = 0; i < oldProductBlocksLength; i++) {
                // Copy all items ignoring the one you want to delete
                if (i != productBlock.getIndexInContainer()) {
                    //&& newArray.length > 0){
                    var pb = productBlocks[i];
                    newArray1[indexCounter] = pb;
                    indexCounter++;
                }
            }
            
            productBlocksContainer.remove(productBlock.getIndexInContainer());//Remove the product block
            productBlocks = newArray1;
            
            // Update the indexs of the product blocks.
            for (int i = 0; i < productBlocks.length; i++) {
                var pb = productBlocks[i];
                pb.setIndexInContainer(i);
            }

            productBlocksContainer.repaint();
            calculateTotal();
        });
    }
    
    protected void calculateTotal(){
        float total = 0;
        var productBlocksLength = productBlocks.length;
        for (int i = 0; i < productBlocksLength; i++) {
            var pb = productBlocks[i];
            var subtotal = pb.getCalculatedSubtotal();
            total += subtotal;
        }
        this.total.setText(String.valueOf(total));
    };
    
    /***
     * Register a new sale.
     * @param evt Event object
     */
    private void submitButtonHandler(java.awt.event.ActionEvent evt0){
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        var now = dtf.format(LocalDateTime.now());
        String productIDs = "";
        String subtotals = "";
        
        //Prepare the String with product IDs and the String with product subtotals.
        for (int i = 0; i < productBlocks.length; i++) {
            productIDs += productBlocks[i].getSelectedProduct().getId() + ",";
            subtotals += productBlocks[i].getCalculatedSubtotal() + ",";
        }
        
        
        
        var db = new DB();
        db.connect();
        
        String[] keys = {"totalAmount","totalProductCount","date","productList","productUnits","user"};
        String[] valuesToInsert = {
            "3500",
            "4",
            String.valueOf(now),
            "4,5",
            "3,1",
            String.valueOf(user.getUsername())
        };
        db.insert("sales", keys, valuesToInsert);
    }
    
    
    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
      submitButtonHandler(evt);
    }//GEN-LAST:event_submitButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterSaleForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel productBlocksContainer;
    private javax.swing.JScrollPane productListContainer;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel total;
    private javax.swing.JLabel totalTitle;
    // End of variables declaration//GEN-END:variables
}
