/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gmasoftware.sellersystem.sales;

import com.gmasoftware.sellersystem.database.DB;
import com.gmasoftware.sellersystem.user.User;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.BoxLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author gonzalo90fa
 */
public class RegisterNewSaleForm extends javax.swing.JFrame {
    private final User user;
//    private JPanel productContainer;
    private DefaultComboBoxModel selectProductModel;
    private int productIndex = 0;
    private JComboBox[] products;
    /**
     * Creates new form RegisterNewSale
     * @param user Authenticated user.
     */
    public RegisterNewSaleForm(User user) {
        this.user = user;
        initComponents();
        this.setLocationRelativeTo(null);
        productContainerFactory();
        selectProductModelFactory();
        addAProduct();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        productContainerB = new javax.swing.JPanel();
        productContainer = new javax.swing.JScrollPane();

        jLabel3.setText("jLabel3");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel6.setText("jLabel6");

        jLabel1.setText("Register new sale");

        submitButton.setText("Accept");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Total");

        productContainerB.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout productContainerBLayout = new javax.swing.GroupLayout(productContainerB);
        productContainerB.setLayout(productContainerBLayout);
        productContainerBLayout.setHorizontalGroup(
            productContainerBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );
        productContainerBLayout.setVerticalGroup(
            productContainerBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 264, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(productContainer))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jLabel5)))
                        .addGap(0, 367, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(productContainerB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 297, Short.MAX_VALUE)
                .addComponent(productContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146)
                .addComponent(jLabel5)
                .addGap(19, 19, 19)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(54, 54, 54)
                    .addComponent(productContainerB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(342, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void productContainerFactory(){
        productContainerB.setBackground(new java.awt.Color(120, 255, 255));
        productContainerB.setLocation(0,0);
        productContainerB.setSize(611, 350);
        var productContainerLayout = new BoxLayout(productContainerB, BoxLayout.Y_AXIS);
        productContainerB.setLayout(productContainerLayout);
        
        JButton addAProductButton = new JButton();
        addAProductButton.setText("Añadir producto");
        addAProductButton.addActionListener((ActionEvent arg0) -> {            
            addAProduct();
        });
        
        productContainerB.add(addAProductButton);
    }
    
    private void selectProductModelFactory(){
        var stock = new com.gmasoftware.sellersystem.stock.Stock();
        var products = stock.getProducts();
        var productsCount = products.length;
        String[] model = new String[productsCount +1];
        model[0] = "Seleccionar";
        for (int i = 0; i < productsCount; i++) {
            var p = products[i];
            model[i+1] = "("+p.getStock()+") "+ p.getName();
        }
        this.selectProductModel = new DefaultComboBoxModel<>(model);
    }

    private void addAProduct(){
        var productRow = new JPanel();
        
        // ComboBox of the products
        JComboBox<String> newProduct = new JComboBox<>();
        newProduct.setModel(selectProductModel);
        var comboBoxTitle = new JLabel();
        comboBoxTitle.setForeground(new java.awt.Color(64, 64, 64));
        comboBoxTitle.setText("Product");
        
        // Product Price
        var  priceTitle = new JLabel();
        var price = new JLabel();
        priceTitle.setForeground(new java.awt.Color(64, 64, 64));
        priceTitle.setText("Price");
        price.setText("0");
        
        // Product Units
        var unitsTitle = new JLabel();
        unitsTitle.setForeground(new java.awt.Color(64, 64, 64));
        unitsTitle.setText("Units");
        var productUnits = new JTextField();
        
        // Product Subtotal
        var subtotalTitle = new JLabel();
        subtotalTitle.setText("Subtotal");
        var subtotal = new JLabel();
        subtotal.setText("0");
        
        // Create Layout and add components
        GroupLayout productRowLayout = new GroupLayout(productRow);
        productRowLayout.setHorizontalGroup(
            productRowLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(productRowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(productRowLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(productRowLayout.createSequentialGroup()
                        .addComponent(newProduct, GroupLayout.PREFERRED_SIZE, 205, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(price, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(productRowLayout.createSequentialGroup()
                        .addComponent(comboBoxTitle, GroupLayout.PREFERRED_SIZE, 203, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(priceTitle, GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(productRowLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addGroup(productRowLayout.createSequentialGroup()
                        .addComponent(unitsTitle, GroupLayout.PREFERRED_SIZE, 114, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(subtotalTitle, GroupLayout.PREFERRED_SIZE, 92, GroupLayout.PREFERRED_SIZE))
                    .addGroup(productRowLayout.createSequentialGroup()
                        .addComponent(productUnits, GroupLayout.PREFERRED_SIZE, 114, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subtotal, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        productRowLayout.setVerticalGroup(
            productRowLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(productRowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(productRowLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxTitle)
                    .addComponent(unitsTitle)
                    .addComponent(priceTitle)
                    .addComponent(subtotalTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(productRowLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(productRowLayout.createSequentialGroup()
                        .addGroup(productRowLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(newProduct, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(productUnits, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(price, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(subtotal, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        
        productRow.setLayout(productRowLayout);
        productRow.add(unitsTitle);
        
        // Add product row (JFrame) to productContainer
//        productContainer.removeAll();
        productContainerB.add(productRow);
//        products = {
//        };
    }
    
    /***
     * Register a new sale.
     * @param evt Event object
     */
    private void submitButtonHandler(java.awt.event.ActionEvent evt0){
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        var now = dtf.format(LocalDateTime.now());
        
        var db = new DB();
        db.connect();
        
        String[] keys = {"totalAmount","totalProductCount","date","productList","productUnits","user"};
        String[] valuesToInsert = {
            "3500",
            "4",
            String.valueOf(now),
            "4,5",
            "3,1",
            String.valueOf(user.getUsername())
        };
        db.insert("sales", keys, valuesToInsert);
    }
    
    
    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
      submitButtonHandler(evt);
    }//GEN-LAST:event_submitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterNewSaleForm(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane productContainer;
    private javax.swing.JPanel productContainerB;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
