/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gmasoftware.sellersystem;

import com.gmasoftware.sellersystem.messages.Alert;
import java.awt.event.KeyEvent;
import com.gmasoftware.sellersystem.user.User;

/**
 *
 * @author GMA Software
 */
public class Login extends javax.swing.JFrame {
    private static Login loginInstance;
    
    private final int windowsWidth = 300;
    private final int windowsHeight = 400;
    
    public static synchronized Login getInstance(){
        if(loginInstance == null){
            loginInstance = new Login();
        }
        return loginInstance;
    }
    
    
    
    /**
     * Creates new form Login
     */
    private Login() {
        initComponents();
        setSize(windowsWidth, windowsHeight);
        setLocationRelativeTo(null);
        com.gmasoftware.sellersystem.theme.Icons.setDefaultFrameIcon(this);
        
        contentPanel.setSize(windowsWidth, windowsHeight);
        
        com.gmasoftware.sellersystem.theme.Styles.applyGoodButtonColos(submitButton);
        com.gmasoftware.sellersystem.theme.Styles.applyNormalButtonFont(submitButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();
        usernameInput = new javax.swing.JTextField();
        passwordInput = new javax.swing.JPasswordField();
        submitButton = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        usernameTitle = new javax.swing.JLabel();
        passwordTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ingresar");
        setResizable(false);

        contentPanel.setPreferredSize(new java.awt.Dimension(300, 400));
        contentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameInput.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usernameInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernameInputKeyPressed(evt);
            }
        });
        contentPanel.add(usernameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 230, 30));

        passwordInput.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passwordInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordInputKeyPressed(evt);
            }
        });
        contentPanel.add(passwordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 230, 30));

        submitButton.setFont(new java.awt.Font("Ubuntu Light", 0, 16)); // NOI18N
        submitButton.setText("INGRESAR");
        submitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitButtonMouseClicked(evt);
            }
        });
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        submitButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                submitButtonKeyPressed(evt);
            }
        });
        contentPanel.add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 230, 40));

        title.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Bienvenido");
        contentPanel.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 230, -1));

        usernameTitle.setBackground(new java.awt.Color(255, 255, 255));
        usernameTitle.setText("Nombre de Usuario");
        contentPanel.add(usernameTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 230, -1));

        passwordTitle.setBackground(new java.awt.Color(255, 255, 255));
        passwordTitle.setText("Contraseña");
        contentPanel.add(passwordTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 230, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButtonMouseClicked
        loginButtonHandler();
    }//GEN-LAST:event_submitButtonMouseClicked

    private void usernameInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameInputKeyPressed
        if (evt.getKeyCode()== KeyEvent.VK_ENTER){
            loginButtonHandler();
        }
    }//GEN-LAST:event_usernameInputKeyPressed

    private void passwordInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordInputKeyPressed
        if (evt.getKeyCode()== KeyEvent.VK_ENTER){
            loginButtonHandler();
        }
    }//GEN-LAST:event_passwordInputKeyPressed

    private void submitButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_submitButtonKeyPressed
        if (evt.getKeyCode()== KeyEvent.VK_ENTER){
            loginButtonHandler();
        }
    }//GEN-LAST:event_submitButtonKeyPressed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitButtonActionPerformed

    private void loginButtonHandler(){
        String typedUsername = usernameInput.getText();
        char[] typedPassword = passwordInput.getPassword();
        
        String passwordStr = "";
        for (char c : typedPassword) {
            passwordStr += c;
        }
        
        User user = User.getInstance();
                
        try{
            user.authenticate(typedUsername, passwordStr);
            
            // I do it for a recommendation in getPassword() documentation.
            passwordStr = null;
            for (int i = 0; i < typedPassword.length; i++) {
                typedPassword[i] = 0;
            }
            
            if(user.isAuthenticated()){
                runHome();
            }
        }catch(Error e){
            switch (e.getMessage()){
                case "no-user":
                    Alert.alert(this, "El usuario ingresado no existe.");
                    break;   
                case "no-password":
                    Alert.alert(this, "La contraseña ingresada es incorrecta.");
                    break;  
                case "cannot-connect-db":
                    Alert.alert(this, "No se ha podido conectar con la base de datos.");
                    break;
                default:     
                    Alert.alert(this, "Ha ocurrido un error desconocido.");
                    throw new AssertionError(); 
            }
        }
    }
    private void runHome(){
        this.setVisible(false);//hide login frame
        
        var mw = MainWindow.getInstance();
        mw.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JLabel passwordTitle;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel title;
    private javax.swing.JTextField usernameInput;
    private javax.swing.JLabel usernameTitle;
    // End of variables declaration//GEN-END:variables
}
