/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gmasoftware.sellersystem;

import com.gmasoftware.sellersystem.theme.Styles;
import com.gmasoftware.sellersystem.user.User;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JScrollPane;
/**
 *
 * @author GMA Software
 */
public class MainWindow extends javax.swing.JFrame {
    private final int contentPanelWidth;
    public int getContentPanelWidth(){
        return this.contentPanelWidth;
    }
    
    /** Single global instance. **/
    private static MainWindow mainWindowInstance = null;
    public static synchronized MainWindow getInstance(){
        if(mainWindowInstance == null){
            mainWindowInstance =  new MainWindow();
        }
        return mainWindowInstance;
    }
    
    /**
     * Creates new form MainWindow
     */
    private MainWindow() {
        initComponents();
        
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        
        //This JFrame
        this.setSize(screenSize.width, screenSize.height);
        setExtendedState(MainWindow.MAXIMIZED_BOTH);
        com.gmasoftware.sellersystem.theme.Icons.setDefaultFrameIcon(this);
        
        contentPanel.setLayout(new BoxLayout(contentPanel,BoxLayout.Y_AXIS));
        
        title.setText("Hola, " + User.getInstance().getUsername() +"!");
        title.setFont(new java.awt.Font("Ubuntu", 1, 28));
        
        mainPanel.setPreferredSize(new Dimension(screenSize.width, mainPanel.getHeight()));
        mainMenu.setPreferredSize(new Dimension((screenSize.width / 4), mainMenu.getHeight()));
        
        contentPanelWidth = contentPanel.getWidth();
        System.out.println("contentPanelWidth " + contentPanelWidth);
        
        permissionRestrictions();
        
        salesButon.setMnemonic(KeyEvent.VK_1);
        stockButon.setMnemonic(KeyEvent.VK_2);
        usersButon.setMnemonic(KeyEvent.VK_3);
        
        Styles.applyNormalButtonColors(salesButon);
        Styles.applyNormalButtonColors(stockButon);
        Styles.applyNormalButtonColors(usersButon);
        Styles.applyNormalButtonFont(salesButon);
        Styles.applyNormalButtonFont(stockButon);
        Styles.applyNormalButtonFont(usersButon);
        Styles.applyNormalButtonFont(closeSesionButton);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        mainMenu = new javax.swing.JPanel();
        salesButon = new javax.swing.JButton();
        stockButon = new javax.swing.JButton();
        usersButon = new javax.swing.JButton();
        closeSesionButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GMA Seller System");
        setBackground(new java.awt.Color(23, 23, 23));
        setMaximumSize(null);
        setMinimumSize(null);
        setResizable(false);
        setSize(new java.awt.Dimension(20, 20));

        title.setFont(new java.awt.Font("Ubuntu Light", 1, 28)); // NOI18N
        title.setText("BIENVENIDO");

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );

        salesButon.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        salesButon.setText("VENTAS");
        salesButon.setMargin(new java.awt.Insets(20, 0, 20, 0));
        salesButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesButonActionPerformed(evt);
            }
        });

        stockButon.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        stockButon.setText("PRODUCTOS");
        stockButon.setMargin(new java.awt.Insets(20, 0, 20, 0));
        stockButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockButonActionPerformed(evt);
            }
        });

        usersButon.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        usersButon.setText("USUARIOS");
        usersButon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        usersButon.setMargin(new java.awt.Insets(20, 0, 20, 0));
        usersButon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        usersButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersButonActionPerformed(evt);
            }
        });

        closeSesionButton.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        closeSesionButton.setText("CERRAR SESIÓN");
        closeSesionButton.setMargin(new java.awt.Insets(20, 0, 20, 0));
        closeSesionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeSesionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainMenuLayout = new javax.swing.GroupLayout(mainMenu);
        mainMenu.setLayout(mainMenuLayout);
        mainMenuLayout.setHorizontalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stockButon, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
            .addComponent(usersButon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(salesButon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(closeSesionButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainMenuLayout.setVerticalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuLayout.createSequentialGroup()
                .addComponent(salesButon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stockButon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usersButon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeSesionButton))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(mainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void stockButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockButonActionPerformed
        var stockView = new com.gmasoftware.sellersystem.stock.StockView();
        var view = stockView.getView();
        this.setNewView(view);
    }//GEN-LAST:event_stockButonActionPerformed

    private void usersButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersButonActionPerformed
        var pl = User.getInstance().getPermissionLevel();
        if(pl == 0 || pl == 1){
            var userView = new com.gmasoftware.sellersystem.user.UserView();
            var view = userView.getView();
            this.setNewView(view);
        }
    }//GEN-LAST:event_usersButonActionPerformed

    private void salesButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesButonActionPerformed
        var salesView = new com.gmasoftware.sellersystem.sales.SalesView();
        var view = salesView.getView();
        this.setNewView(view);
    }//GEN-LAST:event_salesButonActionPerformed

    private void closeSesionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeSesionButtonActionPerformed
        User.destroyInstance();
    }//GEN-LAST:event_closeSesionButtonActionPerformed
    
    /**
     * Put a new view in the content panel.
     * @param view 
     */
    private void setNewView(JScrollPane view){
        contentPanel.setVisible(false);
        contentPanel.removeAll();
        contentPanel.add(view);
        contentPanel.setVisible(true);
    }

    public JButton getSalesButon() {
        return salesButon;
    }

    public JButton getStockButon() {
        return stockButon;
    }

    public JButton getUsersButon() {
        return usersButon;
    }
    
    /**
     * Set the state of the components based on the permission level.
     */
    private void permissionRestrictions(){
        var pl = User.getInstance().getPermissionLevel();
        if(pl > 1){
            switch (pl) {
                case 2: // stock manager
                    salesButon.setEnabled(true);
                    stockButon.setEnabled(true);
                    usersButon.setEnabled(false);
                    break;
                case 3: // sales manager
                    salesButon.setEnabled(true);
                    stockButon.setEnabled(false);
                    usersButon.setEnabled(false);
                    break;
                default: // invalid permission level
                    stockButon.setEnabled(false);
                    salesButon.setEnabled(false);
                    usersButon.setEnabled(false);
            }
        }else{
            //Root and admin
            salesButon.setEnabled(true);
            stockButon.setEnabled(true);
            usersButon.setEnabled(true);
        }
    }
    
    /**
     * Set the main menu buttons to enabled (or disabled if the passed parameter is false). 
     * It is to set the buttons to disabled when the user is editing something to prevent
     * the user from losing unsaved changes.
     * @param isEnabled 
     */
    public void buttonsAreEnabled(boolean isEnabled){
        if(isEnabled){
            // The buttons will be activated based on the user's permission level.
            permissionRestrictions();
        }else{
            //All buttons will be disabled
            salesButon.setEnabled(isEnabled);
            stockButon.setEnabled(isEnabled);
            usersButon.setEnabled(isEnabled);
        }
    }
    
    /**
     * Hide the JFrame and set to null.
     */
    public static void destroyInstance(){
        mainWindowInstance.setVisible(false);
        mainWindowInstance = null;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeSesionButton;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainMenu;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton salesButon;
    private javax.swing.JButton stockButon;
    private javax.swing.JLabel title;
    private javax.swing.JButton usersButon;
    // End of variables declaration//GEN-END:variables
}
