/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gmasoftware.sellersystem.user;

import com.gmasoftware.sellersystem.messages.Alert;

/**
 *
 * @author GMA Software
 */
public class EditUserForm extends javax.swing.JFrame {
    private final UserView userView;
    private Object[] user;
    private final int userID;
    /**
     * Creates new form EditUserForm
     * @param userView
     * @param userID
     */
    public EditUserForm(UserView userView, int userID) {
        this.userView = userView;
        initComponents();
        this.userID = userID;
        loadUserData(userID);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameTitle = new javax.swing.JLabel();
        usernameInput = new javax.swing.JTextField();
        usernameTitle = new javax.swing.JLabel();
        passwordTitle = new javax.swing.JLabel();
        passwordInput = new javax.swing.JPasswordField();
        passwordTitle1 = new javax.swing.JLabel();
        passwordInput1 = new javax.swing.JPasswordField();
        permissionLevelTitle = new javax.swing.JLabel();
        permissionLevelInput = new javax.swing.JComboBox<>();
        saveButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setTitle("Edit User");
        setResizable(false);

        frameTitle.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        frameTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        frameTitle.setText("EDITAR USUARIO");

        usernameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameInputActionPerformed(evt);
            }
        });

        usernameTitle.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        usernameTitle.setText("Nombre de usuario");

        passwordTitle.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        passwordTitle.setText("Nueva contraseña");

        passwordTitle1.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        passwordTitle1.setText("Repetir contraseña");

        permissionLevelTitle.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        permissionLevelTitle.setText("Nivel de permisos");

        permissionLevelInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Gestor de Stock", "Gestor de Ventas" }));

        saveButton.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        saveButton.setText("GUARDAR CAMBIOS");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(233, 2, 2));
        jLabel2.setText("Dejar en blanco para mantener");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(233, 2, 2));
        jLabel3.setText("la contraseña anterior.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usernameInput)
                    .addComponent(usernameTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordInput)
                    .addComponent(passwordTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordInput1)
                    .addComponent(permissionLevelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(permissionLevelInput, 0, 207, Short.MAX_VALUE)
                    .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(frameTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(frameTitle)
                .addGap(18, 18, 18)
                .addComponent(usernameTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(permissionLevelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(permissionLevelInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordTitle)
                .addGap(0, 0, 0)
                .addComponent(jLabel2)
                .addGap(0, 0, 0)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameInputActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        saveButtonHandler();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void loadUserData(int userID){
        user = Users.getUser(userID);
        
        var username = user[1];
        var permissionLevel = Integer.parseInt((String) user[2]);
        
        usernameInput.setText((String) username);
        
        //if it's the root user.
        if(permissionLevel == 0){
            permissionLevelInput.setEnabled(false);
            permissionLevelInput.addItem("Root");
            permissionLevelInput.setSelectedIndex(3);
            return;
        }

        permissionLevelInput.setSelectedIndex(permissionLevel -1);
    }
    
    private void saveButtonHandler(){
        String username = usernameInput.getText();
        int permissionLevel = permissionLevelInput.getSelectedIndex() + 1;
        
        //if it's the root user.
        if(permissionLevel == 4){
            permissionLevel = 0;
        }
                
        char[] password = passwordInput.getPassword();
        char[] repeatedPassword = passwordInput1.getPassword();

        if(password.length > 0 || repeatedPassword.length > 0){
            String passwordStr = "";
            String repeatedPasswordStr = "";
            for (char c : password) {
                passwordStr += c;
            }
            for (char c : repeatedPassword) {
                repeatedPasswordStr += c;
            }

            if(!repeatedPasswordStr.equals(passwordStr)){
                Alert.alert(rootPane, "Las contraseñas ingresadas no coinciden.");
                return;
            }

            //Update the user data. In this case it will update the user's password too.
            Users.updateUser(this.userID, username, passwordStr, String.valueOf(permissionLevel));
            
            // I do it for a recommendation in getPassword() documentation.
            passwordStr = null;
            repeatedPasswordStr = null;
            for (int i = 0; i < password.length; i++) {
                password[i] = 0;
                repeatedPassword[i] = 0;
            }
        }else{
            //Update the user data. In this case it will not update the user's password.
            Users.updateUser(this.userID, username, null, String.valueOf(permissionLevel));
        }
        
        this.setVisible(false);
        userView.reloadTable();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditUserForm(null, 1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel frameTitle;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JPasswordField passwordInput1;
    private javax.swing.JLabel passwordTitle;
    private javax.swing.JLabel passwordTitle1;
    private javax.swing.JComboBox<String> permissionLevelInput;
    private javax.swing.JLabel permissionLevelTitle;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField usernameInput;
    private javax.swing.JLabel usernameTitle;
    // End of variables declaration//GEN-END:variables
}
